# Jekyll _config.yml
title: "Patrick Clery"
email: patrick.clery@gmail.com
description: >-
  Hi, I'm Patrick Clery.
github_username: patrickclery
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Pacific/Vancouver

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-compose
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

github_username: patrickclery
author:
  name   : "Patrick Clery"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Web Development + UI Design + Dev Ops + Project Management"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/patrickclery"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/patrickclery"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/patrickclery"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/patrickclery"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/patrickclery"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/patrickclery"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

timezone: Pacific/Vancouver
lsi: true # Produce an index for related posts. Requires the classifier-reborn plugin.
permalink: /:categories/:title

exclude:
  - .idea

jekyll_compose:
  draft_default_front_matter:
    category:
    collection: posts
    description:
    image:
    published: false
    sitemap: false
    tags:
  post_default_front_matter:
    category:
    description:
    image:
    published: false
    sitemap: false
    tags:
